//------------------------------------------------------------------------------
// <auto-generated>
//     Extracted configuration constants for use outside generated code.
// </auto-generated>
//------------------------------------------------------------------------------

using Substrate.NetApi;
using Substrate.NetApi.Model.Types.Primitive;
using Eterra.NetApiExt.Generated.Storage;
using Eterra.NetApiExt.Generated;

namespace Eterra.Config
{
  public static class EterraConfig
  {
    public static U32 MaxSlotLength { get; private set; }
    public static U32 MaxOptionsPerSlot { get; private set; }
    public static U32 MaxRollsPerRound { get; private set; }
    public static U32 MaxRollHistoryLength { get; private set; }
    public static U32 MaxWeightEntries { get; private set; }

    public static void Initialize(SubstrateClientExt client)
    {
      var constants = new EterraDailySlotsConstants();

      MaxSlotLength = constants.MaxSlotLength();
      MaxOptionsPerSlot = constants.MaxOptionsPerSlot();
      MaxRollsPerRound = constants.MaxRollsPerRound();
      MaxRollHistoryLength = constants.MaxRollHistoryLength();
      MaxWeightEntries = constants.MaxWeightEntries();
    }
  }
}